name: "File existence check"

on: [push, pull_request]

jobs:
  file_existence:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "vtexlab.txt"

      - name: Using my github environment secret
        env:
          VARIAVEL_SUPER_SECRETA: ${{ secrets.VARIAVEL_SUPER_SECRETA }}
        run: echo $VARIAVEL_SUPER_SECRETA

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        # Only runs if all of the files exists
        run: echo file 'vtexlab.txt' exists
      - name: File not exists
        if: steps.check_files.outputs.files_exists == 'false'
        # Only runs if all of the files exists
        run: echo file 'vtexlab.txt' not exists && exit 0
